version: '3.8'

services:
  marketplace:
    container_name: mp-server
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8002:8000
    env_file:
      - ./server/.env.dev